web:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
    - "80:80"

backend:
  build: .
  volumes:
    - .:/code
  links:
    - redis
  environment:
    - PORT_REDIS=6379
    - HOST_REDIS=redis
    - VIRTUAL_HOST=teste.docker

redis:
  image: redis
  volumes:
    - dados_redis:/data
